main_app/urls.py
from django.urls import path
from .views import *


app_name='main_app'

urlpatterns = [
        path('posts/', blogposts, name='allposts'),
        path('posts/add/', addpost, name='addpost'),
        path('posts/editpost/<int:pk>', editpost, name='editpost'),
        path('posts/deletepost/<int:pk>', delpost, name='delpost'),
        path('cats/', blogcats, name='blogcats'),
        path('cats/add/',addcat, name='addcat'),
        path('cats/edit/<int:pk>', editcat, name='editcat'),
        path('cats/delete/<int:pk>', deletecat, name='delcat'),
        path('', startpage, name='startpage'),
    ]

new_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [

    path('', include('main_app.urls')),
    path('social_vk/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts_app.urls')),
    path('shop/', include('shop_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path
from .views import cat_sort, details, startpage_shop


app_name = 'shop_app'

urlpatterns = [
    path('', startpage_shop, name='shopstartpage'),
    path('cat_sorted/<int:pk>/', cat_sort, name='catsort'),
    path('details/<int:pk>/', details, name='details'),
    # path('', AllItemsView.as_view(), name='shopstartpage'),

]

shop_app/models.py
from django.db import models




class BrandModel(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=250, blank=True)
    res1 = models.CharField(max_length=250, blank=True)
    res2 = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f'{self.name}'


class CategoryModel(models.Model):
    name = models.CharField(max_length=250)
    res1 = models.CharField(max_length=250, blank=True)
    res2 = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f'{self.name}'


class WearModel(models.Model):
    brand = models.ForeignKey('BrandModel', on_delete=models.CASCADE)
    category = models.ForeignKey('CategoryModel', on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='media/%Y/%m/%d')
    price = models.PositiveIntegerField(blank=True)
    discount = models.PositiveIntegerField(blank=True, default=0)
    discount_image = models.ImageField(upload_to='%Y/%m/%d', blank=True, null=True)
    popular = models.BooleanField(default=True)
    res2 = models.CharField(max_length=250, blank=True)
    res3 = models.CharField(max_length=250, blank=True)
    res4 = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f'{self.description}'

shop_app/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import ListView
from django.shortcuts import get_object_or_404



# -----------------------Function-Based views------------------------------
def startpage_shop(request):
    categories = CategoryModel.objects.all()
    clothes = WearModel.objects.all()

    context = {'cats':categories, 'clothes':clothes}
    return render(request, 'shop_app/shop_startpage.html', context=context)


def cat_sort(request, pk):
    categories = CategoryModel.objects.all()
    clothes = WearModel.objects.filter(category=pk)

    return render(request, 'shop_app/cat_sorted.html', {'clothes':clothes,'cats':categories,
                                                        })


def details(request, pk):
    info = get_object_or_404(WearModel, pk=pk)
    return render(request, 'shop_app/details.html', {'info':info})

# --------------------------Class_based_views ------------------------------

# class AllItemsView(ListView):
#     model = WearModel
#     context_object_name = 'clothes'
#     template_name = 'shop_app/shop_startpage.html'
#     paginate_by = 8
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super(AllItemsView, self).get_context_data(**kwargs)
#         context['cats'] = CategoryModel.objects.all()[:9]
#         return context

shop_app/templates/shop_app/cat_sorted.html
{% extends 'shop_app/shop_startpage.html' %}
{% load static %}




{% block content %}
<div class="main_div">


{% for item in clothes %}
        <div class="main" style="background-image: url('{{item.image.url}}');">

                <ul class="main_li">
                    <li>{{item.brand}}</li>
                    <li>{{item.description}}</li>
                    <li>{{item.price}} BYN</li>
                    <li><button style="margin-left:45px;">Buy!</button>{{cart_product_form}}
                        <form action="{% url 'shop_app:details' item.pk %}" method="get">
                            <button style="margin-left:40px;">details</button>
                        </form></li>
                </ul>

        </div>
{% endfor %}
</div>




{% endblock %}

shop_app/templates/shop_app/details.html
{% extends 'shop_app/shop_startpage.html' %}
{% load static %}



{% block content %}
<div class="main_div">
        <div class="main_inner">
                <ul style="color:black; list-style-type:none;
                           font-size: 30px;">
                        <li><img style="width:300px;" src="{{info.image.url}}" alt=""></li>
                        <li>{{info.brand}}</li>
                        <li>{{info.description}}</li>
                        <li>{{info.price}} BYN</li>
                </ul>
        </div>
</div>
{% endblock %}

shop_app/templates/shop_app/shop_startpage.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'shopstyles.css' %}">

    <title></title>


</head>
<body >


{% block nav %}
<div class="shopmaindiv">
<table class="table_cats" width="100%"  cellpadding="10px">
    <tr> <td><a href="/">На главную</a></td><td><a href="{% url 'shop_app:shopstartpage' %}"><img style="height:20px" src="/media/Savage2.png" alt=""></a></td>
        <td>Поиск:
            <form action="" method="GET">
                <input type="text">
                <input type="submit" value="search!">
            </form></td>
        <td align="right">Личный кабинет</td>
        <td align="right"><a href=""><img src="/media/shopping-cart4.jpg" width="70px" alt="корзина"></a></td>
    </tr>
</table>
<table width="100%"  cellpadding="10px">
    <tr>{% for cat in cats %}
        <td align="center" class="td_cats"><a style="text-decoration:none;" href="{% url 'shop_app:catsort' cat.id%}">{{cat}}</a></td>
        {% endfor %}
    </tr>
</table>
</div>

{% endblock %}

{% block content %}
<div class="main_div">


{% for item in clothes %}
        <div class="main" style="background-image: url('{{item.image.url}}');">

                <ul class="main_li">
                    <li>{{item.brand}}</li>
                    <li>{{item.description}}</li>
                    <li>{{item.price}} BYN</li>
                    <li><button style="margin-left:45px;">Buy!</button>
                        <form action="{% url 'shop_app:details' item.pk %}" method="get">
                            <button style="margin-left:40px;">details</button>
                        </form>

                    </li>
                </ul>

        </div>
{% endfor %}
</div>

{% endblock %}



{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">prev</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}