accounts_app/urls.py
from django.urls import path, include
from .views import *



app_name='accounts'

urlpatterns = [
    path('registration/', registration, name='register'),
    path('login/', CustomUserLogin.as_view(), name='login'),

    path('logout/', CustomUserLogout.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('editprofile/', edit_profile, name='editprofile'),
    ]

main_app/urls.py
from django.urls import path
from .views import *


app_name='main_app'

urlpatterns = [
        path('posts/', blogposts, name='allposts'),
        path('posts/add/', addpost, name='addpost'),
        path('posts/editpost/<int:pk>', editpost, name='editpost'),
        path('posts/deletepost/<int:pk>', delpost, name='delpost'),
        path('cats/', blogcats, name='blogcats'),
        path('cats/add/',addcat, name='addcat'),
        path('cats/edit/<int:pk>', editcat, name='editcat'),
        path('cats/delete/<int:pk>', deletecat, name='delcat'),
        path('', startpage, name='startpage'),
    ]

new_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [

    path('', include('main_app.urls')),
    path('social_vk/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts_app.urls')),
    path('shop/', include('shop_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path
from .views import cat_sort, details, startpage_shop


app_name = 'shop_app'

urlpatterns = [
    path('', startpage_shop, name='shopstartpage'),
    path('cat_sorted/<int:pk>/', cat_sort, name='catsort'),
    path('details/<int:pk>/', details, name='details'),
    # path('', AllItemsView.as_view(), name='shopstartpage'),

]

main_app/models.py
from django.db import models



class BlogPost(models.Model):
    category = models.ForeignKey('BlogCategory', on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField(max_length=2000, blank=True)
    is_published = models.DateTimeField(auto_now=True)
    is_edited = models.DateTimeField(auto_now_add=True)
    is_moderated = models.BooleanField(default=False)
    is_archivated = models.BooleanField(default=False)
    res = models.CharField(max_length=100,blank=True, null=True)
    res1 = models.CharField(max_length=100,blank=True, null=True)

    def __str__(self):
        return f'{self.title}'

class BlogCategory(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

main_app/forms.py
from django import forms
from .models import BlogCategory, BlogPost



class BlogCategoryForm(forms.ModelForm):
    class Meta:
        model = BlogCategory
        fields = '__all__'

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from .models import BlogCategory, BlogPost
from .forms import BlogCategoryForm, BlogPostForm



def startpage(request):
    context= {'hello':'This is startpage from main_app'}
    return render(request, 'main_app/startpage.html', context)

def blogcats(request):
    cats = BlogCategory.objects.all()

    context={'cats':cats}
    return render(request,'main_app/allcats.html',context=context)

def addcat(request):
    if request.method=='POST':
        form = BlogCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main_app:blogcats')
        else:
            form = BlogCategoryForm(request.POST)
            return render(request,'main_app/addcat.html',{'form':form})
    else:
        form = BlogCategoryForm()
        return render(request, 'main_app/addcat.html', {'form':form})

def editcat(request, pk):
    if request.method == 'POST':
        form = BlogCategoryForm(request.POST)
        if form.is_valid():
            cat = BlogCategory.objects.get(pk=pk)
            cat.name = form.cleaned_data['name']
            cat.description = form.cleaned_data['description']
            cat.save()
            return redirect('main_app:blogcats')
        else:
            return redirect('main_app:editcat')
    else:
        cat = BlogCategory.objects.get(pk=pk)
        form = BlogCategoryForm(instance=cat)
        context = {'form':form, 'cat':cat}
        return render(request, 'main_app/editcat.html', context=context)

def deletecat(request, pk):
    cat = BlogCategory.objects.get(pk=pk)
    cat.delete()
    return redirect('main_app:blogcats')


def blogposts(request):
    posts = BlogPost.objects.all()

    context={'posts':posts}
    return render(request, 'main_app/allposts.html', context=context)

def addpost(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main_app:allposts')
        else:
            form = BlogPostForm(request.POST)
            return render(request, 'main_app:addpost.html', {'form':form})
    else:
        form = BlogPostForm()
        context = {'form':form}
        return render(request, 'main_app/addpost.html', context=context)


def editpost(request,pk):
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            post = BlogPost.objects.get(pk=pk)
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('main_app:allposts')
        else:
            return redirect('main_app:editpost')
    else:
        post = BlogPost.objects.get(pk=pk)
        form = BlogPostForm(instance=post)
        context = {'form':form, 'post':post}
        return render(request, 'main_app/editpost.html', context=context)


def delpost(request,pk):
    post = BlogPost.objects.get(pk=pk)
    post.delete()
    return redirect('main_app:allposts')

main_app/templates/main_app/addcat.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}

    <p>Создание новой категории:</p>
    <p>Название:</p>{{form.name}}
    <p>Описание:</p>{{form.description}}<br><br>
    <input type="submit" value="создать!">
</form>
{% endblock%}

main_app/templates/main_app/addpost.html
{% extends 'main_app/startpage.html' %}
{% load static %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table width="100%" >
        <tr>    <th> Категория: {{form.category}} </th></tr>
        <tr>    <th> Заголовок/тема:{{form.title}} </th></tr>
        <tr>    <th> Содержание:{{form.content}} </th></tr>
        <tr>    <th><input type="submit" value="post!"> <a href="{% url 'main_app:allposts' %}">back</a></th></tr>
    </table>

</form>



{% endblock %}

main_app/templates/main_app/allcats.html
{% extends 'main_app/base.html' %}
{% load static %}


{% block content %}
<table  border="1" cellpadding="7" cellspacing="10">
    <tr>
    <th>Название категории</th>
    <th>  <a class="a_editcat" href="{% url 'main_app:addcat' %}">добавить</a></th>
     <th> </th>
    <th></th>
    </tr>
    {% for cat in cats %}
    <tr>
    <th>{{cat}}</th>
    <th >  </th>
    <th > <a class="a_editcat" href="{% url 'main_app:editcat' cat.id %}">редактировать</a> </th>
    <th > <a class="a_editcat" href="{% url 'main_app:delcat' cat.id %}">удалить</a> </th>
    </tr>

    {% endfor %}
</table>
{% endblock %}

main_app/templates/main_app/allposts.html
{% extends 'main_app/startpage.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<a href="{% url 'main_app:addpost' %}">Добавить пост</a>

{% for post in posts %}

    <table border="1" cellpadding="7" cellspacing="10" width="100%" bgcolor="BlanchedAlmond	">
        <tr>    <th> {{ post.title}}</th>    </tr>
        <tr>    <th>{{post.content}}</th>    </tr>
         <tr>
             <th><a href="{% url 'main_app:editpost' post.pk %}">{% trans "edit post" %}</a>
             <a href="{% url 'main_app:delpost' post.pk %}">удалить пост</a>
             </th>
         </tr>
    </table>

{% endfor %}


{% endblock %}

main_app/templates/main_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="http://userapi.com/js/api/openapi.js" type="text/javascript" charset="windows-1251"></script>

</head>
<body>

    <nav>
        <script type="text/javascript">
        VK.init({
        apiId: YOUR_API_ID
        });
        </script>
        <div id="vk_auth"></div>
        <script type="text/javascript">
        VK.Widgets.Auth('vk_auth', {});
        </script>

        {% block nav %}

        <ul class="topmenu">
        <li><a href="/">Home</a></li>
        <li><a href="">Blog</a>

           <ul class="submenu">
        <li><a href="{% url 'main_app:blogcats' %}">Category</a></li>
         <li><a href="{% url 'main_app:allposts' %}">Posts</a></li>
         <li><a href="">Search</a></li>
         <li><a href="">Archive</a></li>
         </ul>
        </li>
        <li><a href="{% url 'shop_app:shopstartpage' %}">Shop</a>
          <ul class="submenu">
        <li><a href="">GO to products</a></li>
         <li><a href="">Go to basket</a></li>
         <li><a href="">Archive</a></li>
         <li><a href="">e-mail</a></li>
         </ul>
        </li>
        <li><a href="http://127.0.0.1:8000/admin/">Admin site</a></li>
          {% if request.user.is_authenticated %}
             <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
             <li> <p class="greetings">Добро пожаловать, <a href="{% url 'accounts:profile' %}">{{user.profile.user_name.capitalize}}!</a></p></li>
          {% else %}
            <li><a href="{% url 'accounts:register' %}">Registration</a></li>
            <li><a href="{% url 'accounts:login' %}?next={{request.path}}">Log in</a></li>
          {% endif %}
      </ul>
        {% endblock %}
    </nav>


{% block content %}

{% endblock %}


</body>
</html>

main_app/templates/main_app/editcat.html
{% extends 'main_app/base.html' %}
{% load static %}


{% block content %}
<table  cellpadding="7" cellspacing="10">
    <tr>
    <th>Название категории</th>
    <th> </th>
     <th> </th>
    <th></th>
    </tr>
    <form action="" method="POST">
        {% csrf_token %}

    <tr>
    <th>{{cat}}</th>
    <th > Название:{{form.name}} </th>
    <th > Описание:{{form.description}} </th>
    <th ><input type="submit" value="сохранить!"> </th>
    </tr>

    </form>
</table>
{% endblock %}

main_app/templates/main_app/editpost.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <table border="1" cellpadding="7" cellspacing="10" width="100%" bgcolor="BlanchedAlmond	">
                <tr>    <th>Категория: {{form.category}} </th>  </tr>
            <tr>    <th> Заголовок: {{form.title}}</th>   </tr>
            <tr>    <th>Содержание: {{form.content}}</th>   </tr>
            <tr>    <th><input type="submit" value="отправить!">
                <a href="{% url 'main_app:allposts'%}">back</a></th>    </tr>
    </table>

</form>

{% endblock %}

main_app/templates/main_app/startpage.html
{% extends 'main_app/base.html'%}
{% load static %}


{% block content %}




{% endblock %}