accounts_app/urls.py
from django.urls import path, include
from .views import *



app_name='accounts'

urlpatterns = [
    path('registration/', registration, name='register'),
    path('login/', CustomUserLogin.as_view(), name='login'),

    path('logout/', CustomUserLogout.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('editprofile/', edit_profile, name='editprofile'),
    ]

main_app/urls.py
from django.urls import path
from .views import *


app_name='main_app'

urlpatterns = [
        path('posts/', blogposts, name='allposts'),
        path('posts/add/', addpost, name='addpost'),
        path('posts/editpost/<int:pk>', editpost, name='editpost'),
        path('posts/deletepost/<int:pk>', delpost, name='delpost'),
        path('cats/', blogcats, name='blogcats'),
        path('cats/add/',addcat, name='addcat'),
        path('cats/edit/<int:pk>', editcat, name='editcat'),
        path('cats/delete/<int:pk>', deletecat, name='delcat'),
        path('', startpage, name='startpage'),
    ]

new_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [

    path('', include('main_app.urls')),
    path('social_vk/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts_app.urls')),
    path('shop/', include('shop_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class CustomUser(AbstractUser):
    reserv = models.CharField(max_length=100, blank=True)
    reserv2 = models.BooleanField(blank=True, default=False)
    reserv3 = models.CharField(max_length=100, blank=True)
    reserv4 = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.username}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        Profile.objects.get_or_create(user=self)



class Profile(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, primary_key=True)
    user_name = models.CharField(max_length=100, blank=True)
    user_lastname = models.CharField(max_length=150, blank=True)
    avatar = models.ImageField(upload_to='%Y/%m/%d', blank=True, null=True)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=20, blank=True)
    gender = models.CharField(max_length=100, blank=True)
    birthday = models.CharField(max_length=50,blank=True)
    created = models.DateField(auto_now=True)
    reserv = models.CharField(max_length=100, blank=True)
    reserv1 = models.CharField(max_length=100, blank=True)
    reserv2 = models.CharField(max_length=100, blank=True)
    reserv3 = models.CharField(max_length=100, blank=True)
    reserv4 = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.user} profile'

accounts_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser,Profile
from django import forms


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(label ="Пароль",strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'placeholder':'Enter your password..'}))

    password2 = forms.CharField(label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password','placeholder':'Confirm your password..'}), strip=False)

    class Meta:
        model = CustomUser
        fields = ['username']
        help_texts = {'username':'',}
        widgets = {'username': forms.TextInput(attrs={'placeholder':'Enter your login..',
                                                      'label':'Username:'})}


class EditProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar','user_name','user_lastname','email','gender','phone','birthday']
        widgets = {
                    'user_name': forms.TextInput(attrs={'placeholder':'введите имя..',}),
                   'user_lastname': forms.TextInput(attrs={'placeholder':'введите фамилию..',}),
                   'email':forms.EmailInput(attrs={'placeholder':'введите мэйл..',}),
                   'gender':forms.Select(choices=[(None,'выберите пол'),('Мужской','Мужской'),('Женский','Женский')]),
                   'phone':forms.TextInput(attrs={'placeholder':'номер телефона..'}),
                   'birthday':forms.DateInput(attrs={'type':''}),
                   }

accounts_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import CustomUserCreationForm,EditProfile
from .models import CustomUser,Profile
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView,LogoutView


def registration(request):
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            CustomUser.objects.create_user(username=username,
                                           password=password)
            return redirect('accounts:login')
        else:
            return redirect('accounts:register')
    else:
        form = CustomUserCreationForm()
        return render(request, 'accounts/registration.html', context={'form':form})

class CustomUserLogin(LoginView):
    template_name = 'accounts/login.html'



class CustomUserLogout(LogoutView):
    next_page = 'main_app:startpage'

@login_required
def profile(request):
    if request.user.is_staff:
        return redirect('/admin/')
    else:
        profile = Profile.objects.filter(user=request.user)
        context = {'profile':profile}
        return render(request, 'accounts/profile.html', context)

@login_required
def edit_profile(request):
    userprofile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data.get('avatar'):
                userprofile.avatar = form.cleaned_data.get('avatar')
            userprofile.user_name = form.cleaned_data.get('user_name')
            userprofile.user_lastname = form.cleaned_data.get('user_lastname')
            userprofile.email = form.cleaned_data.get('email')
            userprofile.gender = form.cleaned_data.get('gender')
            userprofile.phone = form.cleaned_data.get('phone')
            userprofile.birthday = form.cleaned_data.get('birthday')
            userprofile.save()
            return redirect('accounts:profile')
        else:
            form = EditProfile(request.POST)
            return render(request, 'accounts/editprofile.html', {'form':form})
    else:
        profile = Profile.objects.get(user=request.user)
        data={'user_name':profile.user_name,'user_lastname':profile.user_lastname,'gender':profile.gender,
              'phone':profile.phone,'birthday':profile.birthday,'email':profile.email}
        form = EditProfile(data=data)
        return render(request, 'accounts/editprofile.html', {'form':form,'profile':profile})

accounts_app/templates/accounts/editprofile.html
{% extends 'main_app/base.html'%}
{% load static %}


{% block content %}
<div class="mainprofile">

   <form action="{% url 'accounts:editprofile' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
       <table border="1px" width="100%" height="100%" border-collapse="collapse">


        <tr><td width="150px">{{item.avatar}}{{form.avatar}}</td>
            <td>
                <table width="100%" height="100%" cellpadding="5px">
                <tr class="table-row"><td>Имя: {{item.user_name}}{{form.user_name}}</td></tr>
                <tr class="table-row"><td>Фамилия: {{item.user_lastname}}{{form.user_lastname}}</td></tr>
                <tr class="table-row"><td>Адрес почты: {{item.email}}{{form.email}}</td></tr>
                <tr class="table-row"><td>Пол: {{item.gender}}{{form.gender}}</td></tr>
                <tr class="table-row"><td>Телефон: {{item.phone}}{{form.phone}}</td></tr>
                <tr class="table-row"><td>День рождения: {{item.birthday}}{{form.birthday}}</td></tr>

                <tr class="table-row"><td> <input type="submit" value="Отправить!"></td></tr>
                </table>
            </td>
        </tr>
    </table>

   </form>

</div>
{% endblock %}

accounts_app/templates/accounts/login.html
{% extends 'main_app/base.html'%}
{% load static %}
{% load account socialaccount %}


{% block content %}
{% get_providers as socialaccount_providers %}
    <div class="div_register">
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {% for item in form %}
                <tr> <td>{{item.label}}:</td> <td>{{item}}</td> </tr>
                {% endfor %}
                <tr><td></td><td><input type="submit" value="Log in!"></td></tr>
                <tr><td><a href="{% url 'social:begin' 'auth_backend' %"><img src="/media/VK_Logo.png" width="40px" class="avatar-3" data-toggle="tooltip" ></a></td></tr>
            </table>

        </form>

    </div>
<div class="row">
    <div class="col-md-8 mx-auto social-container my-2 order-md-1">
        <button class="btn btn-danger  mb-2">
            <a href="{% url 'social:begin' 'auth_backend' %}">Login with VK</a>
        </button>
        <button class="btn btn-primary mb-2">
            <a href="">Login with Facebook
            </a>
        </button>
        <button class="btn btn-info mb-2">
            <a href="#">Login with LinkedIn</a>
        </button>
    </div>
</div>
</div>
{% endblock %}

accounts_app/templates/accounts/profile.html
{% extends 'main_app/base.html'%}
{% load static %}


{% block content %}
<div class="mainprofile">
    <table border="1px" width="100%" height="100%" border-collapse="collapse">
   {% for item in profile %}

        <tr><td width="250px"><img src="{% if item.avatar %}{{item.avatar.url}}{% else %}{{'media/2011/no_image.jpg'}}{% endif %}" alt="место под картинку" width="250px"></td>
            <td>
                <table width="100%" height="100%" cellpadding="5px">
                <tr class="table-row"><td>Имя: {% if item.user_name %}{{item.user_name}}{% else %} нажмите редактировать данные{% endif %}</td></tr>
                <tr class="table-row"><td>Фамилия: {% if item.user_lastname %}{{item.user_lastname}}{% else %} нажмите редактировать данные{% endif %}</td></tr>
                <tr class="table-row"><td>Адрес почты: {% if item.email %}{{item.email}}{% else %} нажмите редактировать данные{% endif %}</td></tr>
                <tr class="table-row"><td>Пол: {% if item.gender %}{{item.gender}}{% else %} нажмите редактировать данные{% endif %}</td></tr>
                <tr class="table-row"><td>Телефон: {% if item.phone %}{{item.phone}}{% else %} нажмите редактировать данные{% endif %}</td></tr>
                <tr class="table-row"><td>День рождения: {% if item.birthday%}{{item.birthday}}{% else %} нажмите редактировать данные{% endif %}</td></tr>
                <tr class="table-row"><td><a href="{% url 'accounts:editprofile' %}">редактировать данные</a></td></tr>
                <tr class="table-row"><td></td></tr>
                </table>
            </td>
        </tr>
    </table>
    {% endfor %}


</div>
{% endblock %}

accounts_app/templates/accounts/registration.html
{% extends 'main_app/base.html'%}
{% load static %}



{% block content %}
    <div class="div_register">
        <form action="" method="POST">
            {% csrf_token %}
            <table border="0px" cellpadding="10px" >
                {% for item in form%}
                <tr> <td> {{item.label}}:</td> <td> {{item}} </td></tr>
                {% endfor %}
                <tr><td></td><td><input type="submit" value="Send for registration!"></td></tr>
            </table>


        </form>
    </div>
{% endblock %}